EXAM/main/routes.py
import os
import time
import datetime
import itertools
import json
#import requests
from io import BytesIO
import base64


from flask.wrappers import Response

from flask import render_template, request, redirect, url_for, flash, jsonify, make_response, Blueprint, app, session

from flask_login import login_required
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename
# from newsapi import NewsApiClient

from EXAM.main.forms import create_course_form, PhotoForm

from EXAM.configaration import User_type, camera, user_obj

from EXAM.main.function import created_course_form_db_insertion, delete_exam_attened_exams, delete_old_question_requirements, enroll_students, evaluate_a_question, process_data_for_machine_learning, student_main_page, student_view_courses, teacher_view_courses, webcamera_live_stream

from EXAM.model import Only_file, course_model, enrol_students_model, machine_learning_mcq_model, marksheet, mcqQuestion, mcq_answer_paper, records_of_course_exams, set_exam_question_slot, student_attendence, student_courses_model, teacher_created_courses_model, teacher_posts_model, temporary_model, user_student, user_teacher

from EXAM.users.utils import delete_temporary_collection, remove_junk


main = Blueprint('main', __name__)
instance_path = "/home/b/Desktop/project/CLO_System/EXAM"
# newsapi = NewsApiClient(api_key="0bf80e3a6a5d4fefb6b80ceeaccb9560")
# newsapi = NewsApiClient("https://newsapi.org/v2/top-headlines?country=us&category=technology&apiKey=0bf80e3a6a5d4fefb6b80ceeaccb9560")


@main.route("/live_stream")
# @login_required
def live_stream():
    return Response(webcamera_live_stream(camera()), mimetype='multipart/x-mixed-replace; boundary=frame')


@main.route('/upload', methods=['GET', 'POST'])
def upload():
    form = PhotoForm(CombinedMultiDict((request.files, request.form)))
    if form.validate_on_submit():
        f = form.photo.data
        filename = secure_filename(f.filename)
        f.save(os.path.join(
            instance_path, 'photos', filename
        ))
        return redirect(url_for('index'))

    return render_template('upload.html', form=form)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    # if User_type.user_type == 'admin':
    teachers = user_teacher.objects().all()
    students = user_student.objects().all()
    # context=zip(teachers,students)

    return render_template('admin.html', teachers=teachers, students=students, title='Admin', user_type=User_type.user_type)


main_page_count = 0


@main.route('/main_page', methods=['GET', 'POST'])
@login_required
def main_page():
    # ----------------------------------ekane teacher question evluate krbee
    # delete_exam_attened_exams()
    delete_old_question_requirements()
    teacher_email_id = user_obj.e
    student_id = session['email']

    if User_type.user_type == 'admin':
        return redirect(url_for('main.admin'))

    if User_type.user_type == 'student':
        todays_post, context = student_main_page(student_id)
        if request.method == "POST":
            eroll_key = request.form.get('enroll_key')
            delete_temporary_collection()
            print(eroll_key)
            enroll_students(eroll_key, User_type.user_type)
        exam_results = marksheet.objects(student_email=student_id)

        return render_template('main_page.html', latest_posts_from_teacher=todays_post, exam_results=exam_results, context=context, title='main_page', user_type=User_type.user_type)

    if User_type.user_type == 'teacher':  # ------------------------------------------------TEACHER

        shuffled_question_list, question_part, number_of_question, q_type = process_data_for_machine_learning()
        # print(shuffled_question_list)
        global main_page_count

        # for demo show purpose , question paper bar bar show kora hocche...... and not commented the ######process_data_for_machine_learning method

        # if main_page_count < 2:
        if request.method == "POST":
            difficulty = request.form.get('difficulty')
            if difficulty:
                print(difficulty)
            # ekhane kazzz baki ase-----------------------------------------------------
                evaluate_a_question(shuffled_question_list, question_part,
                                    number_of_question, difficulty, q_type)
            post_title = request.form.get('title')
            post_announcement = request.form.get('announcement')
            post_time = datetime.datetime.now()
            if post_title:
                upload_post = teacher_posts_model()
                upload_post.email = teacher_email_id
                upload_post.title = post_title
                upload_post.announcement = post_announcement
                upload_post.Date = post_time
                upload_post.save()

            # todays_post.append(teacher_posts_model(
            #     title=post_title, announcement=post_announcement, Date=post_time))

            # upload_post = user_teacher(
            #     email=teacher_email_id, post=todays_post)
            # # upload_post.objects(address__country="US").update_one(
            # #     set__posts__S=todays_post(title=post_title,announcement=post_announcement, Date=post_time)
            # # )
            # upload_post.save()

        main_page_count += 1
        return render_template('main_page.html', shuffled_question_list=shuffled_question_list,
                               title='main_page', user_type=User_type.user_type)

    return render_template('main_page.html', title='main_page', user_type=User_type.user_type)


@main.route('/take_a_tour')
def take_a_tour():
    return render_template('views/take_a_tour.html', title='main_page', user_type=User_type.user_type)


@main.route('/guideline')
def guideline():
    return render_template('guideline.html', title='guideline_Page', user_type=User_type.user_type)


@main.route('/guildLineForTeacher')
@login_required
def guildLineForTeacher():
    return render_template('teacher/guildLineForTeacher.html', title='Teacher_guildline', user_type=User_type.user_type)


@main.route('/create_course', methods=['GET', 'POST'])
@login_required
def create_course():
    lessons_len = ''
    form = create_course_form()
    user_type = User_type.user_type
    if request.method == "POST":
        confirm = created_course_form_db_insertion(form, user_type)
        if confirm:
            flash(
                f'{confirm}! Course successfully created, and sended to Admin, for authorization', 'success')
            return redirect(url_for('main.view_courses'))
    return render_template('teacher/create_course.html', title='Create_course', form=form, user_type=user_type)


# javascript kora
@main.route('/view_courses', methods=['GET', 'POST'])
@login_required
def view_courses():
    user_type = User_type.user_type
    usered = user_obj.e  # _P__alias
    # print(usered)
    if user_type == "teacher":
        teacher_view_courses(usered)
        return render_template('views/view_courses.html', title='View courses', user_type=user_type)
    else:
        student_view_courses(usered)
        return render_template('views/view_courses.html', title='View courses', user_type=user_type)


@main.route('/view_course_load_data')
@login_required
def view_course_load_data():
    time.sleep(0.2)

    response_to_browser = ""
    per_scrolling = int(5)
    counter = 0
    datalist = []
    print("Total :", len(course_model.objects()), " Courses registered")

    if request.args:
        c = request.args.get('c')
        count, user_typ = c.split("=")
        print(type(count), " ", count, "  ", user_typ)
        counter = int(count)
        user_type = user_typ
        data_teacher = temporary_model.objects()
        if user_type == 'teacher' and data_teacher is not None:
            if counter == 0:
                print(" first 5 ")
                response_to_browser = make_response(
                    jsonify(temporary_model.objects[:per_scrolling]))
                print(response_to_browser)
            elif counter == len(temporary_model.objects()):
                response_to_browser = make_response(jsonify({}), 200)
                print(response_to_browser)
                print("no more Courses")
            else:
                response_to_browser = make_response(
                    jsonify(temporary_model.objects[counter:counter + per_scrolling]))
                print(f"{counter} to {counter + per_scrolling}")
                print(response_to_browser)
        else:
            data_student = temporary_model.objects()
            if data_student is not None:
                if counter == 0:
                    print(" first 5 ")
                    response_to_browser = make_response(
                        jsonify(temporary_model.objects[:per_scrolling]))
                    print(response_to_browser)
                elif counter == len(temporary_model.objects()):
                    response_to_browser = make_response(jsonify({}), 200)
                    print(response_to_browser)
                    print("no more Courses")
                else:
                    response_to_browser = make_response(
                        jsonify(temporary_model.objects[counter:counter + per_scrolling]))
                    print(f"{counter} to {counter + per_scrolling}")
                    print(response_to_browser)

    return response_to_browser


@main.route('/question_view/<course_code>', methods=['GET', 'POST'])
@login_required
def question_view(course_code):
    course_data = ''
    print(course_code)
    if User_type.user_type == 'student':

        course_code, course_date = course_code.split("=")
        print(course_code, "  DAte", course_date)

        course_data = course_model.objects(
            course_code=course_code, course_duration=course_date).first()
    # questions = []

EXAM/templates/mcq/generateMCQ.html
{% extends "layout.html" %}
{% block body %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<section class="container-fluid my-4">

    <form class=" m-4" method="POST" action="{{url_for('Test_paper.generateMCQ',course_code=course_code)}}"
        enctype="multipart/form-data">

        <header class="text-center" id="linked_course_code" value="{{course_code}}">
            <h2> Arrange a Question Paper for

                {% if corse_code != "teacher" %}
                Course Code : {{course_code}}
                {% endif %}


            </h2>
            <br />

        </header>

        <script>
            // var check=document.getElementById('linked_course_code').getAttribute('value')
            var check = $('#linked_course_code').attr('value')
            console.log(check)
        </script>

        <div class="form-group mt-2">
            <div class="row align-items-start">
                <div class="col-12 col-md-4">
                    {{ form.exam_title.label(class = "form-control-label h4") }}
                    <div class="form-group form-group-inline">
                        {{ form.exam_title(class="form-check", type="radio") }}
                    </div>

                </div>
                <div class="col-12 col-md-8">


                    <legend class="form-control-label h4"> Create a Exam Slot for the Students </legend>
                    <br />
                    <div class="row ">
                        <div class="col-4">
                            {{ form.exam_start_time.label(for="start_time",class ="input-group-append h6")}}
                        </div>

                        <div class="col-8" style="width: 10rem;">
                            <!-- for= appt is a class -->
                            {# {{
                            form.exam_start_time(for="appt",type="time",class="form-control-lg",id="start_time") }}
                            #}
                            <input type="time" class="input-group form-control" id="start_time" name="start_time" />
                        </div>
                    </div>
                    <div class="row gy-2">
                        <div class="col-4">
                            {{ form.exam_end_time.label(for="end_time",class = " input-group-append h6") }}
                        </div>

                        <div class="col-8" style="width: 10rem;">
                            <input type="time" class="input-group form-control" id="end_time" name="end_time" />
                        </div>
                    </div>
                    <div class="row gy-2">
                        <div class="col-4">
                            {{ form.exam_date.label(class ="input-group-append h6")}}
                        </div>

                        <div class="col-8" style="width: 10rem;">
                            {{ form.exam_date(type="date",class="input-group form-control",placeholder=" like:
                            year/month/date") }}
                        </div>
                    </div>
                </div>
            </div>


        </div>


        <div class="form-group mt-2">

            <label for="Textarea" class="form-control-label h4">Example Question paper Caption</label>
            <textarea name="Note:captions" class="form-control" id="Textarea" rows="2"></textarea><br />

        </div>

        <div class="form-group mt-2" style="max-width: 33rem;">

            <div class="form-group">
                {{ form.exam_code.label(class="form-control-label h4") }}
                <br />
                {{ form.exam_code(class="custom-radio form-control") }}
            </div>


        </div>
        <!--div class="form-group">
            {#{ form.exam_marks.label(class="custom-control-label") }#}<br/>
            {#{ form.exam_marks(class="custom-radio") }#}</div>
        </div-->
        <!-- <label class="custom-control-label">Number of Questions :</label><br/>
                        <input id="exam_total_questions" name="exam_total_questions" type="number" class="custom-radio">
                        -->

        {% if corse_code=='teacher' %}


        <div class="form-group mt-2" style="max-width: 33rem;">
            <legend class=" form-control-label h4">Questions for Exam Course</legend>
            <div class="input-group  mb-3 ">

                <input id="course_code" list="course_code_list"
                    class="custom-select custom-select-md mb-3 btn-outline-info form-select"
                    aria-label=".custom-select-lg example" name="course_code" placeholder="Enter Course Code" required>
                <datalist id="course_code_list">
                    {%for codes in course_code %}
                    <option value="{{codes.course_code}}">{{codes.course_code}}</option>
                    {% endfor %}
                </datalist>
                <div class="input-group-append mb-3">
                    <button onclick="GetSelected()" id="btn_course_code" class="btn btn-outline-secondary"
                        type="button">Find
                        lessons</button>
                </div>

            </div>
        </div>


        {% endif %}


        <div class="form-group">

            <label class="form-control-label h4">Question Type</label><br />
            <select class="custom-select form-select btn-outline-info text-center fs-4" name="question_type"
                aria-label="Example select with button addon" required>
                <option type="number" value="mcq">Objective</option>
                <option type="number" value="1">Written</option>
            </select>

        </div>

        <div class="form-group mt-2">
            <div id="lessons_table" class="row table-active"></div>
        </div>

        </div>

        <br />


        <div id="addcard" class="d-flex card-deck">
            <div class="card m-1" style="max-width: 22rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {#{ form.exam_CLO.label(class="custom-control-label") }#}
                        {#{ form.exam_CLO(class="custom-select) }#}
                        <label class="form-control-label h5">
                            Course Outcome </label><br />

                        <input id="exam_CLO" list="clo" name="exam_CLO"
                            class="custom-select form-select custom-select-md mb-3 btn-outline-info "
                            placeholder="Select CLO" autocomplete="off" aria-label=".custom-select-lg example" required>
                        <datalist id="clo">
                            <option selected disabled>Enter the CLO</option>
                        </datalist>
                    </li>

                    </li>

                    <li class="list-group-item">
                        {#{ form.exam_topic.label(class="custom-control-label") }#}
                        {#{ form.exam_topic(class="form-radio",id="exam_topic") }#}
                        <label class="form-control-label h5">
                            Syllabus/Topic/lesson :</label><br />
                        <input id="exam_topic" list="lesson_name" name="exam_topic"
                            class="custom-select form-select custom-select-md mb-3 btn-outline-info "
                            placeholder="Select lesson" autocomplete="off" aria-label=".custom-select-lg example"
                            required>
                        <datalist id="lesson_name">
                            <option selected disabled>
                                Select lesson</option>
                        </datalist>
                    </li>
                    <li class="list-group-item">
                        <label class="form-control-label h5">Question Complexity Level</label>
                        <select class="custom-select form-select btn-outline-info" id="inputGroupSelect04"
                            name="complex_level" autocomplete="off" aria-label="Example select with button addon"
                            required>
                            <option selected disabled="disabled">Select level</option>
                            <option value="1">Low</option>
                            <option value="2">Medium</option>
                            <option value="3">High</option>
                            <option value="5">Very High</option>
                            <option value="10">Insane</option>
                        </select>
                    </li>
                    <li class="list-group-item">
                        <label class="form-control-label h5"> Total_marks </label>
                        <input type="number" class="input-group form-control" id="marks" name="marks"
                            placeholder="For this Lesson" required />
            </div>
            </li>
            </ul>
        </div>



        <div>
            <a href="javascript:void(0);" id="btnAdd" class="btn btn-light mt-3" title="Add clo">
                <img type="button" class=" btn btn-outline-light" src="{{ url_for('static',filename='img/plus.png') }}"
                    style="max-width: 4vh" /> Add more </a>

            <!-- <button type="button" id="btnAdd" class="btn btn-primary">
                            <img type="button" class="btn-outline-light"
                        src="{{ url_for('static',filename='img/plus.png') }}" style="max-width: 4vh"/>
                            
                            ADD </button></div>
                <br/> -->
            <div class="row justify-content-center mt-3">
                <button type="submit" class="btn btn-success fs-5" style="max-width: 60vw;">Generate</button>
            </div>
        </div>


    </form>
    </div>
</section>

<script type="text/javascript" src="{{ url_for('static',filename='generateMCQ.js') }}"> </script>

{% endblock body %}




<!-- ekhane difficulty autogenerate hobe background e -->
<!-- <div class="row">
                    <div class="form-group">
                        <label class="custom-control-label">Question Difficulty</label><br/>
                        <select
                            class="custom-select-sm btn-outline-info"
                            id="inputGroupSelect04"
                            name="question_difficulty"
                            aria-label="Example select with button addon"
                            required>
                        <option selected disabled="disabled">Select difficult level</option>
                        <option type="text" value="Easy">Easy</option>
                        <option type="text" value="Medium">Medium</option>
                        <option type="text" value="Hard">Hard</option>
                        </select>
                    </div>
                </div> -->

EXAM/templates/mcq/mcq_answer_paper.html
{% extends "layout.html" %}
{% block body %}
    <div>
        {#{ mcq_questions }#}
        {# ekhane pura question ase  #}
        <form class="form-control-horizontal" id="submit_answer" enctype="multipart/form-data" action="" method="POST">
            {{ form.hidden_tag() }}
            <p class="h4" id="show_realtime"></p>
            <fieldset class="fieldBox">
                <div class="form-group">
                    {{ form.fullname.label(class= "form-control-label") }}
                    {{ form.fullname(class= "form-control", placeholder="like: Dewan Mohammod Toufik Ali Hassan") }}</div>
                <div class="form-group">{{ form.organization_id.label(class= "form-control-label") }}
                    {{ form.organization_id(class= "form-control" ,placeholder="school or college or workplace id ") }}</div>
                {% set  mcq = mcq_questions.mcq_question.question_dictionary %}
                {% set count = [1] %}
                {% for i in mcq %}
                    <div class="form-group changelist-form-container " style="color:#1b1e21">
                        <div class="col-form-label" style="-moz-transform:initial">
                            <article class="h5" value="{{ i }}" name="q{{ count }}={{ i }}"><b>{{ i }} </b></article>
                        </div>
                        {% for j in mcq[i] %}
                            <div class="form-check-inline ">
                                <input class="radio-inline form-check-inline " type="radio" name="answer{{ count }}"
                                       value="{{ j }}">
                                <label class="form-check-inline "> {{ j }}</label>
                            </div>
                        {% endfor %}
                        {% if count.append(count.pop() + 1) %}{% endif %}
                    </div>
                {% endfor %}
                {{ form.submit(class="btn btn-outline-info") }}
            </fieldset>
        </form>
        {#{ mcq_questions.exam_date}#}
        {% set dat = "Jan 26, 2021 17:40:25" %}
        <p class="hide" id="date" value="{{ exam_date }}"></p>
        <p id="time" value="{{ exam_end_time }}"></p>

    </div>
    <script type="text/javascript" src="{{ url_for('static', filename="countdown.js") }}"
            crossorigin="anonymous"></script>

{% endblock %}

EXAM/templates/mcq/mcq_answer_session.html
{% extends 'layout.html' %}

{% block body %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<style>
       .unselectable {
              -webkit-user-select: none;
              -webkit-touch-callout: none;
              -moz-user-select: none;
              -ms-user-select: none;
              user-select: none;
              
            }
</style>



<p id="ending_time_of_exam" value="{{ending_time_of_exam}}" hidden>{{ending_time_of_exam}}</p>
<legend class="h2 btn-outline-info text-right" id="timmer"></legend>

<h5 class="flash text-center"> Remote Supervision(auto surveillance) is on ... </h5>
<div class="text-center">
       <img class="img-thumnail" src="{{ url_for('main.live_stream') }}" alt="surveillance"
              style="max-height: 10vh;">
</div>



<!-- timmer -->



<!-- <script>
       var parsed = JSON.parse('{#{question_mcq_for_current_session | tojson}#}');
       console.log(parsed);
</script> -->

{#{question_mcq_for_current_session}#}

       <form action="" method="POST" class="form-horizontal container" enctype="multipart/form-data">


              <br>

              <div class="card-block bg-light unselectable">
                     <div class="card-header ">
                            {{question_part}}
                     </div>
                     <div class="card-body h6">
                            {%for op in option_list%}

                            <div class="card-text text-secondary">
                                   <input id="chk {{op}}" aria - label="Checkbox for following text input"
                                          type="radio" value="{{op}}"
                                          name="selected_option" />

                                   <label for="chk {{op}}"> {{op}}</label>
                            </div>

                            {%endfor%}
                     </div>
              </div>

              {#{confrimation}#}



              <div class="text-center"><br>
                     <button class='btn btn-secondary' id="btn_submit" name="submit" type="submit"> Confirm
                            Answer & Next</button>
              </div>






       </form>



       <script>
       // Set the date we're counting down to
       //var countDownDate = new Date("Jan 5, 2022 15:37:25").getTime();

       const ending_time_of_exam = document.getElementById("ending_time_of_exam").getAttribute("value");


       countDownDate_end = new Date(ending_time_of_exam + "").getTime();

       // Update the count down every 1 second
       var x = setInterval(function () {

              // Get today's date and time
              var now = new Date().getTime();

              // Find the distance between now and the count down date
              var distance = countDownDate_end - now;

              // Time calculations for days, hours, minutes and seconds
              var days = Math.floor(distance / (1000 * 60 * 60 * 24));
              var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
              var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
              var seconds = Math.floor((distance % (1000 * 60)) / 1000);

              // Output the result in an element with id="demo"
              document.getElementById("timmer").innerHTML = hours + "h  "
                     + minutes + "m  " + seconds + "s  " ;

              // If the count down is over, write some text 
              if (distance < 0) {
                     clearInterval(x);
                     document.getElementById("timmer").innerHTML = "EXPIRED";
                     document.getElementById("btn_submit").submit();
              }
       }, 1000);
</script>


       {% endblock body %}




























       <!-- <script>

       $(document).ready(function () {
              load();
       });

       function load() {
              $('#add_data').focus();
              $('#btn_next_question').focus();
              $('#question_card').focus();
              var next_count = 1;
              var parse = 0;


              var questions = JSON.parse('{{question_mcq_for_current_session | tojson}}');
              console.log(questions);
              var viewQuestion = '';
              var question_block = $('#add_data');
              //var selected_option = $('#')

       $('#btn_next_question').click(function () {
              $('#question_card').empty();
              $('#add_data').empty();



   fetch(`/answer_session_load?c=${next_count}`).then(function (response) { response.json().then(function (recived_next_count) {
              $('#count').html(recived_next_count);
              console.log(typeof(recived_next_count));

       

              });
  });
});
}  

</script> -->






       <!--<script language="JavaScript" type="text/javascript" src="{#{ url_for('static',filename='answer_session.js') }#}">
 </script>-->

EXAM/templates/mcq/mcqan.html
{% extends 'layout.html' %}
{% block body %}
    <div>
        {#{ mcq_questions }#}
        {# ekhane pura question ase  #}
        <form class="form-control-horizontal" id="submit_answer" enctype="multipart/form-data" action="" method="POST">
            {{ form.hidden_tag() }}
            <p class="h4" id="show_realtime"></p>
            <fieldset class="fieldBox">
                <div class="form-group">
                    {{ form.fullname.label(class= "form-control-label") }}
                    {{ form.fullname(class= "form-control", placeholder="like: Dewan Mohammod Toufik Ali Hassan") }}</div>
                <div class="form-group">{{ form.organization_id.label(class= "form-control-label") }}
                    {{ form.organization_id(class= "form-control" ,placeholder="school or college or workplace id ") }}</div>
                {% set  mcq = mcq_questions.mcq_question.question_dictionary %}
                {% set count = [1] %}
                {% for i in mcq %}
                    <div class="form-group changelist-form-container " style="color:#1b1e21">
                        <div class="col-form-label" style="transform:initial">
                            <article class="h5" value="{{ i }}" name="q{{ count }}={{ i }}"><b>{{ i }} </b></article>
                        </div>
                        {% for j in mcq[i] %}
                            <div class="form-check-inline ">
                                <input class="radio-inline form-check-inline " type="radio" name="answer{{ count }}"
                                       value="{{ j }}">
                                <label class="form-check-inline "> {{ j }}</label>
                            </div>
                        {% endfor %}
                        {% if count.append(count.pop() + 1) %}{% endif %}
                    </div>
                {% endfor %}
                {{ form.submit(class="btn btn-outline-info") }}
            </fieldset>
        </form>
        {#{ mcq_questions.exam_date}#}
        {% set dat = "Jan 26, 2021 17:40:25" %}
        <p class="hide" id="date" value="{{ mcq_questions.exam_date }}"></p>
        <p id="time" value="{{ mcq_questions.exam_end_time }}"></p>

    </div>
    <script type="text/javascript" src="{{ url_for('static', filename="countdown.js") }}"
            crossorigin="anonymous"></script>

{% endblock body %}
{#%  %#}
