EXAM/main/routes.py
import os
import time
import datetime
import itertools
import json
#import requests
from io import BytesIO
import base64


from flask.wrappers import Response

from flask import render_template, request, redirect, url_for, flash, jsonify, make_response, Blueprint, app, session

from flask_login import login_required
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename
# from newsapi import NewsApiClient

from EXAM.main.forms import create_course_form, PhotoForm

from EXAM.configaration import User_type, camera, user_obj

from EXAM.main.function import created_course_form_db_insertion, delete_exam_attened_exams, delete_old_question_requirements, enroll_students, evaluate_a_question, process_data_for_machine_learning, student_main_page, student_view_courses, teacher_view_courses, webcamera_live_stream

from EXAM.model import Only_file, course_model, enrol_students_model, machine_learning_mcq_model, marksheet, mcqQuestion, mcq_answer_paper, records_of_course_exams, set_exam_question_slot, student_attendence, student_courses_model, teacher_created_courses_model, teacher_posts_model, temporary_model, user_student, user_teacher

from EXAM.users.utils import delete_temporary_collection, remove_junk


main = Blueprint('main', __name__)
instance_path = "/home/b/Desktop/project/CLO_System/EXAM"
# newsapi = NewsApiClient(api_key="0bf80e3a6a5d4fefb6b80ceeaccb9560")
# newsapi = NewsApiClient("https://newsapi.org/v2/top-headlines?country=us&category=technology&apiKey=0bf80e3a6a5d4fefb6b80ceeaccb9560")


@main.route("/live_stream")
# @login_required
def live_stream():
    return Response(webcamera_live_stream(camera()), mimetype='multipart/x-mixed-replace; boundary=frame')


@main.route('/upload', methods=['GET', 'POST'])
def upload():
    form = PhotoForm(CombinedMultiDict((request.files, request.form)))
    if form.validate_on_submit():
        f = form.photo.data
        filename = secure_filename(f.filename)
        f.save(os.path.join(
            instance_path, 'photos', filename
        ))
        return redirect(url_for('index'))

    return render_template('upload.html', form=form)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    # if User_type.user_type == 'admin':
    teachers = user_teacher.objects().all()
    students = user_student.objects().all()
    # context=zip(teachers,students)

    return render_template('admin.html', teachers=teachers, students=students, title='Admin', user_type=User_type.user_type)


main_page_count = 0


@main.route('/main_page', methods=['GET', 'POST'])
@login_required
def main_page():
    # ----------------------------------ekane teacher question evluate krbee
    # delete_exam_attened_exams()
    delete_old_question_requirements()
    teacher_email_id = user_obj.e
    student_id = session['email']

    if User_type.user_type == 'admin':
        return redirect(url_for('main.admin'))

    if User_type.user_type == 'student':
        todays_post, context = student_main_page(student_id)
        if request.method == "POST":
            eroll_key = request.form.get('enroll_key')
            delete_temporary_collection()
            print(eroll_key)
            enroll_students(eroll_key, User_type.user_type)
        exam_results = marksheet.objects(student_email=student_id)

        return render_template('main_page.html', latest_posts_from_teacher=todays_post, exam_results=exam_results, context=context, title='main_page', user_type=User_type.user_type)

    if User_type.user_type == 'teacher':  # ------------------------------------------------TEACHER

        shuffled_question_list, question_part, number_of_question, q_type = process_data_for_machine_learning()
        # print(shuffled_question_list)
        global main_page_count

        # for demo show purpose , question paper bar bar show kora hocche...... and not commented the ######process_data_for_machine_learning method

        # if main_page_count < 2:
        if request.method == "POST":
            difficulty = request.form.get('difficulty')
            if difficulty:
                print(difficulty)
            # ekhane kazzz baki ase-----------------------------------------------------
                evaluate_a_question(shuffled_question_list, question_part,
                                    number_of_question, difficulty, q_type)
            post_title = request.form.get('title')
            post_announcement = request.form.get('announcement')
            post_time = datetime.datetime.now()
            if post_title:
                upload_post = teacher_posts_model()
                upload_post.email = teacher_email_id
                upload_post.title = post_title
                upload_post.announcement = post_announcement
                upload_post.Date = post_time
                upload_post.save()

            # todays_post.append(teacher_posts_model(
            #     title=post_title, announcement=post_announcement, Date=post_time))

            # upload_post = user_teacher(
            #     email=teacher_email_id, post=todays_post)
            # # upload_post.objects(address__country="US").update_one(
            # #     set__posts__S=todays_post(title=post_title,announcement=post_announcement, Date=post_time)
            # # )
            # upload_post.save()

        main_page_count += 1
        return render_template('main_page.html', shuffled_question_list=shuffled_question_list,
                               title='main_page', user_type=User_type.user_type)

    return render_template('main_page.html', title='main_page', user_type=User_type.user_type)


@main.route('/take_a_tour')
def take_a_tour():
    return render_template('views/take_a_tour.html', title='main_page', user_type=User_type.user_type)


@main.route('/guideline')
def guideline():
    return render_template('guideline.html', title='guideline_Page', user_type=User_type.user_type)


@main.route('/guildLineForTeacher')
@login_required
def guildLineForTeacher():
    return render_template('teacher/guildLineForTeacher.html', title='Teacher_guildline', user_type=User_type.user_type)


@main.route('/create_course', methods=['GET', 'POST'])
@login_required
def create_course():
    lessons_len = ''
    form = create_course_form()
    user_type = User_type.user_type
    if request.method == "POST":
        confirm = created_course_form_db_insertion(form, user_type)
        if confirm:
            flash(
                f'{confirm}! Course successfully created, and sended to Admin, for authorization', 'success')
            return redirect(url_for('main.view_courses'))
    return render_template('teacher/create_course.html', title='Create_course', form=form, user_type=user_type)


# javascript kora
@main.route('/view_courses', methods=['GET', 'POST'])
@login_required
def view_courses():
    user_type = User_type.user_type
    usered = user_obj.e  # _P__alias
    # print(usered)
    if user_type == "teacher":
        teacher_view_courses(usered)
        return render_template('views/view_courses.html', title='View courses', user_type=user_type)
    else:
        student_view_courses(usered)
        return render_template('views/view_courses.html', title='View courses', user_type=user_type)


@main.route('/view_course_load_data')
@login_required
def view_course_load_data():
    time.sleep(0.2)

    response_to_browser = ""
    per_scrolling = int(5)
    counter = 0
    datalist = []
    print("Total :", len(course_model.objects()), " Courses registered")

    if request.args:
        c = request.args.get('c')
        count, user_typ = c.split("=")
        print(type(count), " ", count, "  ", user_typ)
        counter = int(count)
        user_type = user_typ
        data_teacher = temporary_model.objects()
        if user_type == 'teacher' and data_teacher is not None:
            if counter == 0:
                print(" first 5 ")
                response_to_browser = make_response(
                    jsonify(temporary_model.objects[:per_scrolling]))
                print(response_to_browser)
            elif counter == len(temporary_model.objects()):
                response_to_browser = make_response(jsonify({}), 200)
                print(response_to_browser)
                print("no more Courses")
            else:
                response_to_browser = make_response(
                    jsonify(temporary_model.objects[counter:counter + per_scrolling]))
                print(f"{counter} to {counter + per_scrolling}")
                print(response_to_browser)
        else:
            data_student = temporary_model.objects()
            if data_student is not None:
                if counter == 0:
                    print(" first 5 ")
                    response_to_browser = make_response(
                        jsonify(temporary_model.objects[:per_scrolling]))
                    print(response_to_browser)
                elif counter == len(temporary_model.objects()):
                    response_to_browser = make_response(jsonify({}), 200)
                    print(response_to_browser)
                    print("no more Courses")
                else:
                    response_to_browser = make_response(
                        jsonify(temporary_model.objects[counter:counter + per_scrolling]))
                    print(f"{counter} to {counter + per_scrolling}")
                    print(response_to_browser)

    return response_to_browser


@main.route('/question_view/<course_code>', methods=['GET', 'POST'])
@login_required
def question_view(course_code):
    course_data = ''
    print(course_code)
    if User_type.user_type == 'student':

        course_code, course_date = course_code.split("=")
        print(course_code, "  DAte", course_date)

        course_data = course_model.objects(
            course_code=course_code, course_duration=course_date).first()
    # questions = []

EXAM/templates/admin.html
{% extends "layout.html" %}
{% block body %}



<div class="container">
    <legend> Active Users </legend>
    <br/>
    <div class="">
        <legend>Teachers</legend>
        <div class="table">
            {%for tech in teachers%}
            <div class="row table-secondary table-bordered table-responsive-lg ">
                <div class="col">
                    {{tech.user_name}}
                </div>
                <div class="col ">
                    {{tech.email}}
                </div>
                <div class="col">
                    {{tech.organization_id}}
                </div>
            </div>
            <br/>
            {%endfor%}
        </div>

        <legend>Students</legend>
        <div class="table">
            {%for student in students%}
            <div class="row table-secondary table-bordered table-responsive-lg">
                <div class="col">
                    {{student.user_name}}
                </div>
                <div class="col ">
                    {{student.email}}
                </div>
                <div class="col">
                    {{student.organization_id}}
                </div>
            </div>
            <br/>
            {%endfor%}
        </div>

    </div>
</div>





{% endblock body %}

EXAM/templates/admin_notice.html
{%extends "layout.html"%}
{%block body%}


<section class="container">
    <form class=" container" action="" method="POST" enctype="multipart/form-data">

        <legend class="card-header">
            Notice For Fellow Teacher....
        </legend>
        <div class="card-body">
            <div class="form-group">
                <label for="title" class="custom-control-label"> Notice Title</label>
                <input type="text" class="form-control" id="title" name="title">
            </div>

            <div class="form-group">
                <label for="announcement" class="custom-control-label">Notice </label>
                <textarea type="textarea" class="form-control" rows="10" cols="50" id="announcement" name="announcement">
             </textarea>
            </div>
        </div>


        <div class="card-footer" style="top: 3vh;">
            <button class="btn btn-info" type="submit"> Post The Notice!</button>
        </div>
    </form>

</section>


{%endblock body%}

EXAM/templates/count_Down.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="container">
<style>
    .content {
        max-width: 750px;
        box-sizing: border-box;
        margin: auto;
        background: rgb(254, 255, 243);
        padding: 200px;
    }
    .content container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        display: flex;
    }

    .dash {
        margin: 0 15px;
        width: 35px;
        height: 15px;
        border-radius: 8px;
        background: #f7eb4c;
        box-shadow: 0 0 10px 0 #FECDFF;
    }

    .uno {
        margin-right: -18px;
        transform-origin: center left;
        animation: spin 3s linear infinite;
    }

    .dos {
        transform-origin: center right;
        animation: spin2 3s linear infinite;
        animation-delay: .2s;
    }

    .tres {
        transform-origin: center right;
        animation: spin3 3s linear infinite;
        animation-delay: .3s;
    }

    .curator {
        transform-origin: center right;
        animation: spin4 3s linear infinite;
        animation-delay: .4s;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        25% {
            transform: rotate(360deg);
        }
        30% {
            transform: rotate(370deg);
        }
        35% {
            transform: rotate(360deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    @keyframes spin2 {
        0% {
            transform: rotate(0deg);
        }
        20% {
            transform: rotate(0deg);
        }
        30% {
            transform: rotate(-180deg);
        }
        35% {
            transform: rotate(-190deg);
        }
        40% {
            transform: rotate(-180deg);
        }
        78% {
            transform: rotate(-180deg);
        }
        95% {
            transform: rotate(-360deg);
        }
        98% {
            transform: rotate(-370deg);
        }
        100% {
            transform: rotate(-360deg);
        }
    }

    @keyframes spin3 {
        0% {
            transform: rotate(0deg);
        }
        27% {
            transform: rotate(0deg);
        }
        40% {
            transform: rotate(180deg);
        }
        45% {
            transform: rotate(190deg);
        }
        50% {
            transform: rotate(180deg);
        }
        62% {
            transform: rotate(180deg);
        }
        75% {
            transform: rotate(360deg);
        }
        80% {
            transform: rotate(370deg);
        }
        85% {
            transform: rotate(360deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    @keyframes spin4 {
        0% {
            transform: rotate(0deg);
        }
        38% {
            transform: rotate(0deg);
        }
        60% {
            transform: rotate(-360deg);
        }
        65% {
            transform: rotate(-370deg);
        }
        75% {
            transform: rotate(-360deg);
        }
        100% {
            transform: rotate(-360deg);
        }
    }

</style>

<section class="container">
    <div>
        <p id="exam_date" value="{{ starting_time_of_exam }}"></p>
        <div>
            <div class="card text-center">
                <div class="btn btn-outline-warning">
                    <div class="content card-body">
                        <h4 class="card-title"> <b> Exam will be open in </b></h4>
                        <hgroup class="h1" id="show_realtime"></hgroup>
                        <h4 class="card-subtitle">Prepare yourself </h4><br>
                        <br><br>
                        <div class="row container">
                            <div class="col dash uno"></div>
                            <div class="col dash dos"></div>
                            <div class="col dash tres"></div>
                            <div class="col dash curator"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<section>
    <div>

    </div>
</section>
</body>
<script type="text/javascript" src="{{ url_for('static', filename="countdown.js") }}" crossorigin="anonymous">
</script>
</html>

EXAM/templates/examiner.html
{%extends "layout.html"%}
{%block body%}


<section class="shadow-sm btn-group-horizental">
  <div class="container">
    <article class="mx-auto">
      <br />
      <h3 class="mt-3">  Setup a Written Question </h3>
      <a type="button" class=" btn btn-outline-secondary btn-lg btn-block d-grid gap-2  fs-3" href="{{url_for('Test_paper.wrqu')}}">Written Question Paper </a> 
      <br/>
      <h3 class="mt-3"> Setup a Mcq Question</h3>
      <a type="button" class=" btn btn-outline-secondary btn-lg btn-block d-grid gap-2 fs-3" href="{{url_for('Test_paper.mcqqu_sub')}}">MCQ Question Paper (Your defined)</a>
      <br/>
      <h3 class="mt-3"3 class="mt-3"> Upload Mcq Questions in Question bank </h3>
      <a type="button" class=" btn btn-outline-secondary btn-lg btn-block d-grid gap-2 fs-3" href="{{url_for('Test_paper.mcq_upload',course_code=user_type)}}">MCQ Question Upload </a>
      <br/>
      <h3 class="mt-3">  Request a Mcq Question Paper</h3>
      <a type="button" class=" btn btn-outline-secondary btn-lg btn-block d-grid gap-2 fs-3" href="{{url_for('Test_paper.generateMCQ',course_code=user_type)}}">Request a MCQ (Machine Generate)</a>
      <p> ........</p>
    </article>
  </div>

</section>

<section class="container">
  <legend> <b> Notice Board </b></legend>
  <br/>
  {% for notice in notices %}

  <div class="card text-white bg-secondary mb-3 ">
    <div class="card-header">
      <div class="row">
        <div class="col-8" style="background-color: rgb(101, 100, 100);">
          <p>{{notice.notice_title}}</p>
        </div>
        <div class="col-4">
          <p>{{notice.notice_time}}</p>
        </div>

      </div>
    </div>
    <br>
    <div class="body container">
      <p>{{notice.notice_announcement}}</p>
    </div>
  </div>
  {%endfor%}
</section>



{%endblock body%}

EXAM/templates/guideline.html
{% extends 'layout.html' %}
{% block body %}

{% endblock %}

EXAM/templates/layout.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

 

    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.3.1/css/all.css'>

    <link rel="preconnect" href="https://fonts.gstatic.com">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Pattaya&display=swap">


    <!-- <link rel="icon" href="data:,"> -->



    <!--Amar CSS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/starterTemplate.css') }}">
    {#% assets "scss_all" %#}
    <!--link rel=stylesheet type=text/css href="{#{ASSET_URL }#}"-->
    {#% endassets %#}
    {% if title %}
    <title>EXAM-{{ title }}</title>
    {% else %}
    <title>EXAM</title>
    {% endif %}
</head>


<!-- Navigation  NAVVVVVVVVVVVVVVV section start  -->




<body>

    <header class="container-fluid">
        <!-- Navigation  NAVVVVVVVVVVVVVVV part start  -->


        <nav class="navbar navbar-expand-lg fixed-top">

            <section class="container">

                <button class="navbar-toggler ms-2" type="button" data-toggle="collapse"
                    data-target="#navbarTogglerDemo03">
                    <span class="navbar-toggler-icon "></span>
                </button>
                <div class="navbar-header">
                    <a class="navbar-brand ms-sm-2 ms-md-0 fw-bold fs-3" style="color: var(--main-color);"
                        href="{{ url_for('main.index') }}">
                        Exams!!
                        <img class="img-fluid" style="max-height: 2rem; max-width: 5vw;"
                            src="{{url_for('static',filename="img/Exam_logo.png")}}" />
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav nav-tabs mt-2 mt-lg-0 text-center fs-6">
                        <li class="nav-item ">
                            <a class="nav-link" href="{{ url_for('main.main_page') }}">Home </a>
                        </li>

                        {% if user_type == 'admin' %}
                        <li class="nav-item ">
                            <a class="nav-link" href="{{ url_for('users.create_notice') }}">
                                Notices</a>
                        </li>
                        {% endif %}

                        {% if user_type == 'teacher' %}
                        <li class="nav-item ">
                            <a class="nav-link" href="{{ url_for('main.create_course') }}">Create-Course</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{{ url_for('main.view_courses') }}">View-courses</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{{ url_for('main.course_assigned_students') }}">My-Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.examiner') }}">Examiner</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.guildLineForTeacher') }}">Teacher-guildLine</a>
                        </li>

                        {% endif %}
                        {% if user_type == 'student' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.student_dashboard') }}">Exam-Schedule</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.view_courses') }}">Enrolled-Courses</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('Test_paper.model_test') }}">Test your Brain</a>
                        </li>

                        <!-- <li class="nav-item">
                        <a class="nav-link" href="{#{ url_for('main.live_stream') }#}">Webcam</a>
                    </li> -->

                        {% endif %}




                    </ul>
                    <!--<form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>-->
                </div>
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        {% if user_type == 'student' %}
                        {% block navenrol %}

                        {% endblock navenrol %}
                        {% endif %}

                        <a type="button" class="nav-item nav-link btn btn-danger p-2 me-sm-2 me-md-0" href="{{ url_for('users.logout') }}">Log out</a>

                        {% else %}

                        <a type="button" class="nav-item nav-link me-sm-2 me-md-0"
                            href="{{ url_for('users.login') }}">Login</a>

                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Sign Up</a>
                        {% endif %}
                    </div>
                

            </section>
        </nav>


    </header>



    <section class="container-fluid">
        <section class="container mt-5 pt-2">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} mt-2">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            <section class="row mt-3">

                {% if current_user.is_authenticated %}
                {% if user_type == 'teacher' %}
                <div class="col-12 mt-4 text-end">
                    <h4>Teacher Page</h4>
                </div>

                {% endif %}
                {% if user_type == 'student' %}
                <div class="col-12 mt-4 text-end">
                    <h4>Student Page</h4>
                </div>
                {% endif %}
                {% else %}
                <span></span>
                {% endif %}

            </section>
        </section>
    </section>













    {% block body %}

    {% endblock body %}

    <!-- Custom Script -->
    <!--script type="text/javascript" src="{{ url_for('static',filename='bootstrap_bundle.js') }}"></script>-->
    <!-- jQuery -->
    <!-- <script>
    function enrol(){
            const URL = '/enrol'
            const xhr = new XMLHttpRequest();
            sender = JSON.stringify(selected)
            xhr.open('POST', URL);
            xhr.send(sender)
    }
    </script>-->



</body>



















<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    defer></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
    defer></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"
    defer></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script-->

<script>
    $(document).ready(function () {

        $('ul.navbar-nav > li')
            .click(function () {
                $('ul.navbar-nav > li')
                    .removeClass('active text-light');
                $(this).addClass('active  text-danger');
            });

        $('body').bind('cut copy', function (e) {
            e.preventDefault();
        });

    });
</script>





<!-- <footer>
    <div class="row justify-content-around bg-transparent">
        <div class="col-4">
            <p>This is an app for online exam developed by bashar</p>
        </div>
        <div class="col-4">
            <p>Ekhane web info deya Hobe Under construction</p>
        </div>
    </div>

</footer> -->

EXAM/templates/login.html
{% extends "layout.html" %}
{% block body %}

<!-- <h3 class="text-center text-white pt-5">Login form</h3> -->
<div class="loginParent d-flex justify-content-center align-items-center ">

    <form class="loginChid form-group " action method="post">
        <legend class="text-primary mb-3 h1 fw-semibold"> Login </legend>

        {{ form.email.label(class="form-control-label") }} 
        
        {{ form.email(class="form-control mt-2",type="email",placeholder="Your email address...")
        }}

        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}

        <br />
        {{ form.password.label(class="form-control-label") }}
        <br />
        {{ form.password(placeholder="Your password...",type="password",class="form-control
        custom-control-lg mt-2") }}
        <br />

        <div class="form-check mb-2">
            {{form.remember(class="form-check-input  ") }}
            {{form.remember.label(class="form-check-label") }}
        </div>


        {{ form.submit(class="form-group btn btn-primary mb-2") }}
        <div class="d-grid">
            <small class=" text-muted ml-2 mb-2">
                <a href="{{url_for('users.reset_request')}}"> Forgot Password?
                </a>
            </small>
            <small id="register-link" class=" text-muted ml-2 text-right">
                <a href="{{ url_for('users.register') }}" class="text-info">Register
                    here</a>
            </small>
        </div>
    </form>
</div>

{% endblock body %}

EXAM/templates/reset_password.html
{% extends 'layout.html' %}

{% block body %}

<section class=" shadow-sm btn-group-horizontal container">
    <form method="POST" action="" class="form-group" enctype="multipart/form-data">
        <fieldset>
        {{ form.hidden_tag() }}
        <br/>
        <legend> Enter your Registered Email</legend>
        {{ form.email.label(class="form-group") }}
        <br/>
        {{ form.email(class="form-control", type="email", placeholder="Your email address...") }}
        <br/>
        <!-- {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %} -->
        </fieldset>
        {{ form.submit(class="form-group btn btn-outline-info") }}
        <a href="{{ url_for('main.index') }}"" class="form-group btn btn-info">go back to homepage</a>

    </form>
</section>



{% endblock body %}

EXAM/templates/sample.html
{% extends 'layout.html' %}

{% block body %}
    <h1>{{title}}</h1>
{% endblock body %}
    