EXAM/users/routes.py
from flask.wrappers import Response
from EXAM import bcrypt
from flask import render_template, request, redirect, url_for, flash, Blueprint, session
from flask_login import current_user, logout_user, login_required, login_user

from EXAM import bcrypt
from EXAM.configaration import User_type, user_obj
from EXAM.model import admin_notice_model, course_model, enrol_students_model, student_courses_model, temp_student_collection, temporary_model, user, user_student
from EXAM.users.forms import (
    enrolForm,
    registration_form,
    LoginForm,
    forgetPasswordForm,
    resetPasswordForm,
    searchForm,
)
from EXAM.users.utils import (
    register_method,
    sending_email_to_user,
    sending_mail_to_user_for_course_enroll_key, delete_temporary_collection
)
import time
import datetime

users = Blueprint("users", __name__)


@users.route("/registration", methods=["GET", "POST"])
def register():
    form = registration_form()
    if current_user.is_authenticated:
        return redirect(url_for("main.main_page"))

    if request.method == "POST":
    #if form.validate_on_submit():
        check = register_method(form)
        if check == "done":
            return redirect(url_for("users.login"))
    return render_template("registration.html", title="Registration", form=form)


# klasd@gmail.com
# 4306985567


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.main_page"))
    form = LoginForm()
    # email = form.email.data
    # password = form.password.data
    # print(form.password.data)
    if request.method == "POST":
        if form.email.data:
            # if form.validate_on_submit():
            # print('email'+student_usersd.email, student_usersd['password'])
            usersd = user.objects.filter(email=form.email.data).first()  # eta NOSQL er part
            if usersd and bcrypt.check_password_hash(
                usersd.password, form.password.data
            ):
                # print(usersd['email'], usersd['password'])
                if usersd.user_category == "student":
                    User_type.user_type = "student"
                    user_obj.e = usersd["email"]
                    session['email'] = usersd["email"]
                elif usersd.user_category == "admin":
                    session['email'] = ''
                    User_type.user_type = "admin"
                    user_obj.e = usersd["email"]
                    #session['email'] = usersd["email"]
                else:
                    session['email'] = ''
                    User_type.user_type = "teacher"
                    user_obj.e = usersd["email"]
                    session['course_date'] = ''
                login_user(usersd, remember=form.remember.data)
                next_page = request.args.get("next")
                # return check
                flash(
                    f"আপনার উপর শান্তি বর্ষিত হোক.... {usersd.user_name}", "success")
                if usersd.user_category == "admin":
                    return (
                        redirect(next_page)
                        if next_page
                        else redirect(url_for("main.admin"))
                    )
                else:
                    return (
                        redirect(next_page)
                        if next_page
                        else redirect(url_for("main.main_page"))
                    )
                # return check
            else:
                flash(f"Login Unsuccessful !!!", "danger")
                print("Data NAi")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    collection = temporary_model.objects().all()
    collection.delete()
    return redirect(url_for("main.main_page"))


@users.route("/account")
@login_required
def account():
    return redirect(url_for("main.main_page"))


@users.route("/reset_password", methods=(["GET", "POST"]))
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.main_page"))
    form = forgetPasswordForm()
    
    if request.method == 'POST':
        #print(request.form['email'])
        User = user.objects(email=request.form['email']).first()
        #print(User)
        sending_email_to_user(User)
        flash("An Email has been sent with instruction to reset your password ", "info")

    elif form.validate_on_submit():
        #print(form.data)
        User = user.objects(email=form.email.data).first()
        #print(User)
        sending_email_to_user(User)
        flash("An Email has been sent with instruction to reset your password ", "info")

    return render_template("reset_password.html", title="change_password", form=form)


@users.route("/reset_password/<token>", methods=(["GET", "POST"]))
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.main_page"))
    User = user.verify_reset_token(token)
    if User is None:
        flash("that is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = resetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        User.password = hashed_password
        User.save()
        flash("Your Password has been updated ! Now you can login with new password")
        return redirect(url_for("users.login"))
    return render_template(
        "reset_token.html", title="Verify_password_for_user", form=form
    )


@users.route("/create_notice", methods=(["GET", "POST"]))
@login_required
def create_notice():
    notice_title = request.form.get('title')
    notice_announcement = request.form.get('announcement')
    notice_time = datetime.datetime.now()
    if request.method == "POST":
        if notice_title:
            upload_notice = admin_notice_model()
            upload_notice.notice_title = notice_title
            upload_notice.notice_announcement = notice_announcement
            upload_notice.notice_time = notice_time
            upload_notice.save()

    return render_template(
        "admin_notice.html", title="Examiner_Page", user_type=User_type.user_type)


@users.route("/examiner")
@login_required
def examiner():
    # kaz ase -=---------------------------------------------------
    notices = admin_notice_model.objects().order_by("-notice_time")
    return render_template(
        "examiner.html", title="Examiner_Page", notices=notices, user_type=User_type.user_type)


@users.route("/student_list/<course_code>", methods=["GET", "POST"])
# @login_required
def student_list(course_code):
    # delete_temporary_collection()
    form = searchForm()
    enrolled_students = list()
    students = ''
    selected_data = ""
    result_students = ""
    corse_code, course_date = course_code.split("=")
    print(course_code, "  DAte", course_date)
    #corse_code = course_code
    check = ""
    # students=''
    enroll_key = form.enroll_key.data
    if request.method == "POST":
        delete_temporary_collection()
        print(enroll_key)
        organization_id = form.organization_id.data
        result_students = user_student.objects(organization_id=organization_id).first()
        if result_students:
            return render_template(
                "student/student_list.html",
                form=form,
                title="Students",
                user_type=User_type.user_type,
                result_students=result_students,
            )
        email_list = request.form.getlist('students_list_checkbox')
        #print(email_list)
        sending_mail_to_user_for_course_enroll_key(
            email_list, enroll_key, corse_code)
        return redirect(url_for('main.view_courses'))
        # enroll kora polapain er email ase
    delete_temporary_collection()

    for students_enrolled in enrol_students_model.objects(course_code=corse_code):
        if students_enrolled not in enrolled_students:
            enrolled_students.append(
                students_enrolled.enrolled_students_id)

    for userStudents in user_student.objects():
        student_temp_class = temp_student_collection()
        student_temp_class.user_name = userStudents.user_name
        student_temp_class.email = userStudents.email
        student_temp_class.organization_id = userStudents.organization_id
        student_temp_class.save()

    for aleady_enrolled in enrolled_students:
        user_already = temp_student_collection.objects(
            email=aleady_enrolled)
        print(f"already ase {aleady_enrolled}")
        user_already.delete()

    students = temp_student_collection.objects()
    return render_template(
        "student/student_list.html",
        form=form,
        title="Students",
        user_type=User_type.user_type,
        students=students,
        course_date=course_date,
        course_code=course_code,
    )


# '''if request.args:
#    c = request.args.get('c')
#         # selected_data = json.loads(request.args.get("email_list"))
#   flash(f'A mail with a enroll Has been send to the Students', 'success')
#       return redirect(url_for('main.main_page'))'''
"""@users.route("/enrol", methods=["GET", "POST"])
# @login_required
def enrol():
   eroll_key=request.form['enroll_key']
   enroll_students(eroll_key,User_type.user_type)
   return redirect(url_for("main.main_page"))
   
   # render_template("student/enrol.html", title=" Students", user_type=User_type.user_type)
"""

EXAM/templates/question_view/exams_view.html
{%extends "layout.html"%}
{%block body%}

<legend class="text-info text-center" 
style="position:fixed; top:50vh; left:0; right:0; bottom:0;"> 
These are the Exams, Which are hosted by you.</legend>
{#% set course_code,course_date=course_code.split("=") %#}
{#{course_code}#}
<section class="container">
    
    {%for i in passed_course_exams %}
    <div class="card text-dark bg-light mb-3 ">
        <div class="card-header ">
            <div id="course_code" value="{{i.course_code}}">
                Course :
                {{i.course_code}}
            </div>

        </div>
        <div class="card-body card-text ">
            {% set l_info = i.exam_secret_code %}
            <p id="data" value="{{l_info}}"></p>
            <a id="link" class="card-block stretched-link text-decoration-none" 
            href="{{url_for('main.course_exams_students',link_info=l_info)}}"></a>

            <p> The Exam Title : </p>  {{i.exam_title}}
        </div>
        <div class="card-footer text-right ">
            Hosted at : {{i.entry_date}}
            
        </div>
    </div>
    <br>
    {% set l_info = "none" %}
    {%endfor%}

</section>



<script>
      $(window).scroll(function () {
            if ($(this).scrollTop() > 135) {
                $('#task_flyout').addClass('fixed');
            } else {
                $('#task_flyout').removeClass('fixed');
            }
        });
</script>


{%endblock body%}

<!-- href="{{url_for('main.course_exams_students',link_info=l_info)}}" -->
<!-- href='http://course_exams_students/{{l_info}}'></a>  -->
<!--  -->

EXAM/templates/question_view/students_answer_sheet.html
{%extends "layout.html"%}
{%block body%}


{#{link_info}#}

{#{answer_sheets}#}
{#% set course_code,course_date=course_code.split("=") %#}
{#{course_code}#}
{%set temp =''%}
{%set question = answer_sheets.question_dictionary_type_list%}

<section class="">


    {%for (i,k,l) in
    iter.zip_longest(question,answer_sheets.selected_answer_options,answer_sheets.correct_answer)%}





    <div class="card">
        {#% set vid_name = 'files/'+ v %#}

                <div class="card-header">
                    {%set temp = i | string %} {#{temp}#}

                    {%set temp_ques, temp_op = temp.strip("}{").split(":")%} {#{i}#}

                    <h5> {{temp_ques}} </h5>
                </div>
                <div class="card-body">
                    <div class="row container">
                        {% set temp_op = temp_op.strip("][")%}
                        <h5>Option :</h5>
                        {%for item in temp_op.strip("[").split("'") %}
                        <div class="col">{{ item }}</div>
                        {%endfor%}
                    </div>
                </div>







                <div class="card-footer">
                    <div class="card-text"> Choosen by student : {{k}} </div>
                    <div class="card-text text-right">
                        Correct_answer : {{l}}
                    </div>
                </div>



            </div>

    <br>
    {%endfor%}



</section>






{%endblock body%}


<!-- {#% set video_file_surveilence = Only_file.objects(v_id=v).first()%}
        {% set vid = BytesIO(video_file_surveilence.binary_file.read())%}
        {% set str_equivalent_video = base64.b64encode(vid.getvalue()).decode()%#} -->


        <!-- <video width="400" height="180"
                    controls>
                    <source src="data:video/x-msvideo;base64,{#{str_equivalent_video}#}" type="video/mp4">
                <source src="/home/b/Desktop/CLO_system/EXAM/static/files/{{v}}" type="video/x-msvideo"> 
                <source src="{#{url_for('static',filename=vid_name)}#}" type="video/x-msvideo" > 
                </video> -->

EXAM/templates/question_view/students_of_exam_slots.html
{%extends "layout.html"%}
{%block body%}
{#{link_info}#}
<style>
    .img_tag{
        height: 45px; 
        width: 45px ;
        border-radius: 50%;

    }
</style>
<div class="container">
    <legend>The students, Those who attend the Exam.</legend><br>
    <a class="row active btn-outline-info">
        <div class="col-2"></div>
        <div class="col-5">Students Name</div>
        <div class="col-5">Students Email ID</div>
    </a>
    <br>
    {%for students in attended_students%}
   
    

  {%set objects_of_student = user_student.objects(email=students.student_email).first() %}
        {% set pic = BytesIO(objects_of_student.profile_pic.read())%}
        {% set pic_content = objects_of_student.profile_pic.content_type %}
        
        {% set str_equivalent_image = base64.b64encode(pic.getvalue()).decode()%}


   
  

   
    {% set l_info = students.exam_secret_code+"="+students.student_email %}
    <a class="row shadow-sm" href="{{url_for('main.course_exams_students_answer_sheet',link_info=l_info)}}"
        style="text-decoration: none;">
        <div class="col-2">
            <img class="img_tag img-thumbnail " src="data:{{pic_content}};base64,{{str_equivalent_image}}" alt="profile picture">
            <!-- <img src="{#{url_for('static',filename='temp/'+pic_file_name)}#}" alt="Ase nai Photo"> -->
        </div>
        <div class="col-5 ">{{students.student_name}}</div>
        <div class="col-5 ">{{students.student_email}}</div>
    </a>
    <br>
    {% set l_info = "none" %}
   
        
    {%endfor%}
</div>
{%endblock body%}

<!-- {#% set fd = open("/home/b/Desktop/project/EXAM/static/temp"+ pic_file_name, 'wb') %#}
        
         
    {#%set fd= fd.write(photo) %#}
    {#%set fd= fd.close() %#}

 new_file("/home/b/Desktop/project/EXAM/static/temp",filename="pic_file_name") -->
<!-- Kaz baki Ase---------------------------------- -->

EXAM/templates/question_view/view_questions.html
{% extends "layout.html" %}
{% block body %}

{% if user_type=='teacher' %}




<div class="shadow-lg btn-group-horizontal">
    {#{ form.hidden_tag() }#}
    <header>
        <div class="row justify-content-end flex-wrap text-center"> 
            <div class="col-3">
                <a href="{{ url_for('Test_paper.mcq_upload',course_code=course_code) }}" class="btn btn-primary btn-block"
                    role="button" aria-pressed="true">Upload new Question</a>
            </div>
            <div class="col-2">
                <a href="{{ url_for('Test_paper.generateMCQ',course_code=course_code) }}" class="btn btn-primary " role="button"
                    aria-pressed="true">Generate Question </a>
            </div>
            <!--  <a href="{#{ url_for('main.Lessons')}#}" class="btn btn-secondary " role="button"aria-pressed="true">Add lessons</a>-->
            <div class="col-2 ">
                <a href="{{ url_for('main.course_exams',course_code=course_code ) }}" class="btn btn-primary " role="button"
                    aria-pressed="true">View regular performence</a>
            </div>
            <div class="col-2 ">
                <a href="{{ url_for('users.student_list',course_code=course_code ) }}" class="btn btn-primary " role="button"
                    aria-pressed="true">All Students</a>
            </div>
           
        </div>

        {% set course_code,course_date=course_code.split("=") %}

    </header>
    <legend style="margin-left: 5vh;">MCQ Questions Bank
        <small class="h6" style="margin-left: 8vh;">{{ course_code }}</small> {#{course_date}#}
    </legend>

</div>


<div class="section">
    <br>
    {% set j=[1] %}
    {% for i in mcqQuestion.objects(
    course_code=course_code) %}
    <div class="table-active table-responsive-lg">
        <p><b>Question{{ j }} </b>:-- {{ i.question }} ?<br /></p>
    </div>
    {% if j.append(j.pop() + 1) %}{% endif %}
    {% endfor %}

</div>



{% endif %}

{% if user_type == 'student' %}


<section class="body container">
    <div class=" text-center container ">
        <div class="header text-warning">
            <h2>{{course_data.course_title}}</h2>
        </div>
        <p class="title text-info">
            <br />
            <legend>Code: "{{course_data.course_code}}" </legend>

        </p>
        <div class="body container">

            <div class="text">
                <legend>Course Outcome</legend>
                
                {%for course_co in course_data.course_co %}

                <div class=" tr text-center">
                    {{course_co}}
                </div>
                {%endfor%}
                <br />
                <legend> Lessons </legend>
                
                {%for course_lesson in course_data.course_lessons %}
                
                <div class="tr text-center">
                    {{course_lesson}}

                </div>
                {%endfor%}

                <div class="text">
                    <article>
                        <br />
                        <legend>Description</legend>
                        
                        {{course_data.course_caption}}
                    </article>
                    <br>
                </div>

            </div>

        </div>
        <div class="footer text-warning">
            <legend>Expire Date</legend>
            {{course_data.course_duration}}
        </div>
    </div>
</section>


{% endif %}



{% endblock body %}